[package]
name = "nexus"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.37"
log = "0.4.27"
nix = { version = "0.30.1", features = ["user"] }
pam = "0.8.0"
rpassword = "7.4.0"
whoami = "1.6.0"
