[package]
name = "elev"
version = "0.5.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = "4.5.37"
log = "0.4.27"
nix = { version = "0.30.1", features = ["user"] }
pam-client2 = "0.5.2"
regex = "1.11.1"
rpassword = "7.4.0"
syslog = "7.0.0"
whoami = "1.6.0"
